framework:
    rate_limiter:
        self_registration:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
        change_password:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
