security:
    password_hashers:
        App\Entity\Auth\User: 'bcrypt'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Auth\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: voter_login
                check_path: voter_login
                username_parameter: login[user]
                password_parameter: login[pass]
                enable_csrf: true
                default_target_path: listChallengesMenu
            logout:
                path: voter_logout
                target: listChallengesMenu

    access_control:
        - { path: ^/vote/, roles: ROLE_VOTER }
