services:
  challengeator-app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      COUCHDB_URL: http://admin:admin@challengeator-couch:5984
    volumes:
      - ./:/var/www
      - ~/.composer/cache:/root/.composer/cache
      - ~/.ssh:/root/.ssh
    working_dir: /var/www
    networks:
      - challengeator

  couch-db:
    image: couchdb:3
    container_name: challengeator-couch
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - challengeator

  nginx:
    image: nginx:1.25-alpine
    container_name: challengeator-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - challengeator

networks:
  challengeator:
    driver: bridge

volumes:
  couchdb_data:
