services:
  challengeator-app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      COUCHDB_URL: http://admin:admin@challengeator-couch:5984
      DATABASE_URL: mysql://challengerator:challengerator@challengeator-mariadb:3306/challengerator?serverVersion=10.11
    depends_on:
      - challengeator-mariadb
    volumes:
      - ./:/var/www
      - ~/.composer/cache:/root/.composer/cache
      - ~/.ssh:/root/.ssh
    working_dir: /var/www
    networks:
      - challengeator

  challengeator-mariadb:
    image: mariadb:10.11
    container_name: challengeator-mariadb
    environment:
      MYSQL_DATABASE: challengerator
      MYSQL_USER: challengerator
      MYSQL_PASSWORD: challengerator
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - challengeator

  couch-db:
    image: couchdb:3
    container_name: challengeator-couch
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - challengeator

  mailpit:
    image: axllent/mailpit:latest
    container_name: challengeator-mailpit
    ports:
      - "8025:8025"
    networks:
      - challengeator

  nginx:
    image: nginx:1.25-alpine
    container_name: challengeator-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - challengeator

networks:
  challengeator:
    driver: bridge

volumes:
  couchdb_data:
  mariadb_data:
