index:
    path: /
    controller: App\Controller\ChallengeController::index

# -----------------------------------------------
# Auth routes:
loginMenu:
    path: /login/{challengeName}
    controller: App\Controller\AuthController::loginFormPage

voter_login:
    path: /voter-login
    controller: App\Controller\AuthController::voterLogin
    methods: [GET, POST]

voter_logout:
    path: /voter-logout

admin_login:
    path: /admin-login/{challengeName}
    controller: App\Controller\AuthController::adminLogin
    methods: [POST]

addSelfRegisteredVoterToChallengeFormPage:
    path: /challenge/signup/{challengeName}/{selfRegistrationCode}
    controller: App\Controller\AuthController::addSelfRegisteredVoterForChallengePage

voter_accept_invite:
    path: /invitation/{token}
    controller: App\Controller\AuthController::acceptInvite
    methods: [GET, POST]

changePasswordMenu:
    path: /voter/changePass
    controller: App\Controller\AuthController::changePasswordForVoter

# -----------------------------------------------
# Challenge routes:
listChallengesMenu:
    path: /challenges
    controller: App\Controller\ChallengeController::listChallengesMenu

createChallengeMenu:
    path: /challenge/new
    controller: App\Controller\ChallengeController::createChallenge

startChallenge:
    path: /challenge/initialize/{challengeName}
    controller: App\Controller\ChallengeController::startChallenge
    methods: [POST]

addCarToChallengeFormPage:
    path: /challenge/addCarForm/{challengeName}
    controller: App\Controller\ChallengeController::carsDashboardPage

addVoterToChallengeFormPage:
    path: /challenge/addVoterForm/{challengeName}
    controller: App\Controller\ChallengeController::votersDashboardPage

toggleSelfRegistrationForChallenge:
    path: /challenge/toggleSelfRegistration/{challengeName}
    controller: App\Controller\ChallengeController::toggleSelfRegistrationForChallenge
    methods: [POST]

resetVotesForVoterOnChallenge:
    path: /challenge/resetVoter/
    controller: App\Controller\ChallengeController::resetVotesForVoterOnChallenge
    methods: [POST]

deleteVoterFromChallenge:
    path: /challenge/deleteVoter/{challengeName}/{voterId}
    controller: App\Controller\ChallengeController::deleteVoterFromChallenge

# -----------------------------------------------
# Voting routes:
voteDashboardForUser:
    path: /vote/{challengeName}
    controller: App\Controller\VotingController::votingDashBoardForUser
    methods: [GET]

voteCarForUser:
    path: /vote/{challengeName}
    controller: App\Controller\VotingController::voteForCarForUser
    methods: [POST]

# -----------------------------------------------
# Upload routes:
listFile:
    path: /uploader/list/{folderId}
    controller: App\Controller\UploadController::listFilesFromGoogleDrive

uploadFile:
    path: /uploader/upload
    controller: App\Controller\UploadController::uploadFileToMyDriveForm

uploadFileToDrive:
    path: /uploader/uploaded
    controller: App\Controller\UploadController::uploadFileToDrive
