# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    couchDsn: '%env(resolve:COUCHDB_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # App\Repository\ChallengeRepositoryInterface:
    #     class: App\Repository\Couch\CouchChallengeRepository
    #     arguments:
    #         $dsn: '%couchDsn%'

    # App\Repository\CarRepositoryInterface:
    #     class: App\Repository\Couch\CouchCarRepository
    #     arguments:
    #         $dsn: '%couchDsn%'

    # App\Repository\VoterRepositoryInterface:
    #     class: App\Repository\Couch\CouchVoterRepository
    #     arguments:
    #         $dsn: '%couchDsn%'

    # App\Repository\InviteCodeRepositoryInterface:
    #     class: App\Repository\Couch\CouchInviteCodeRepository
    #     arguments:
    #         $dsn: '%couchDsn%'

    App\Repository\ChallengeRepositoryInterface:
        class: App\Repository\Doctrine\DoctrineChallengeRepository

    App\Repository\CarRepositoryInterface:
        class: App\Repository\Doctrine\DoctrineCarRepository

    App\Repository\VoterRepositoryInterface:
        class: App\Repository\Doctrine\DoctrineVoterRepository

    App\Repository\InviteCodeRepositoryInterface:
        class: App\Repository\Doctrine\DoctrineInviteCodeRepository

    App\Services\ChallengeService:
        arguments:
            $votesLogger: '@monolog.logger.votes'
            $loginsLogger: '@monolog.logger.logins'

    App\Repository\StorageResourceRepositoryInterface:
        class: App\Repository\Doctrine\DoctrineStorageResourceRepository

    App\Services\GoogleDriveService:
        arguments:
            $clientId: '%env(GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
